// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultCosmosLibrary.accountsContainerName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultCosmosLibrary.accountsIDName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultCosmosLibrary.countersContainerName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultCosmosLibrary.countersIDName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultCosmosLibrary.smsContainerName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultCosmosLibrary.smsIDName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultCosmosLibrary.whatsappContainerName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultCosmosLibrary.whatsappIDName")]
[assembly: SuppressMessage("Usage", "CA2211:Non-constant fields should not be visible", Justification = "<Pending>", Scope = "member", Target = "~F:SMSAndWhatsAppDeploymentTool.ResourceHandlers.CosmosResourceHandler.found")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultDataverseLibrary.api")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultDataverseLibrary.metadataEmailAccount")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultDataverseLibrary.metadataEmailNonAccount")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultDataverseLibrary.metadataFrom")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultDataverseLibrary.metadataMessage")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultDataverseLibrary.metadataPhoneNumberID")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultDataverseLibrary.metadataPicPath")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultDataverseLibrary.metadataTimestamp")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultDataverseLibrary.metadataTo")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultCosmosLibrary.phoneContainerName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultCosmosLibrary.phoneIDName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultCosmosLibrary.whatsappphoneContainerName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultCosmosLibrary.whatsappphoneIDName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONCreateAppSettings.settings")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONCreateAppSettings.Settings.authTenant")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONCreateAppSettings.Settings.clientId")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONCreateAppSettings.Settings.clientSecret")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONCreateAppSettings.Settings.tenantId")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultDataverseLibrary.metadataDisplayName")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONDefaultDataverseLibrary.metadataPhoneNumber")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONGetDataverseEnvironments.odatacontext")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONGetDataverseEnvironments.value")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.contentVersion")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Metadata.description")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Metadata1.description")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Metadata2.description")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Metadata3.description")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Name.defaultValue")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Name.metadata")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Name.type")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.parameters")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Parameters.name")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Parameters.prin")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Parameters.role")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Parameters.storageAccounts")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Prin.defaultValue")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Prin.metadata")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Prin.type")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Properties.principalId")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Properties.roleDefinitionId")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Resource.apiVersion")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Resource.dependsOn")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Resource.kind")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Resource.location")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Resource.name")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Resource.properties")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Resource.scope")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Resource.sku")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Resource.type")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.resources")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Role.defaultValue")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Role.metadata")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Role.type")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.schema")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Sku.name")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Storageaccounts.defaultValue")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Storageaccounts.metadata")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:SMSAndWhatsAppDeploymentTool.JSONParsing.JSONRoleAssignments.Storageaccounts.type")]
